// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	AccountNumber string           `json:"account_number"`
	Balance       int64            `json:"balance"`
	Currency      string           `json:"currency"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Entry struct {
	ID            uuid.UUID        `json:"id"`
	AccountID     uuid.UUID        `json:"account_id"`
	Amount        int64            `json:"amount"`
	TransactionID pgtype.UUID      `json:"transaction_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Transaction struct {
	ID          uuid.UUID        `json:"id"`
	AccountID   uuid.UUID        `json:"account_id"`
	Amount      int64            `json:"amount"`
	Type        string           `json:"type"`
	ReferenceID pgtype.UUID      `json:"reference_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Transfer struct {
	ID            uuid.UUID        `json:"id"`
	FromAccountID uuid.UUID        `json:"from_account_id"`
	ToAccountID   uuid.UUID        `json:"to_account_id"`
	Amount        int64            `json:"amount"`
	Status        pgtype.Text      `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	FullName     string           `json:"full_name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
