server:
  name: SimpleBank
  env: local
  port: 8002

database:
  driver: postgres
  host: localhost
  port: 5432
  name: Simple_Bank
  user: admin
  password: nnphan2126
  sslmode: disable

security:
  jwt:
    secret: 123456
  salt: 123456
