server:
  name: SimpleBank
  env: local
  port: 8002

database:
  driver: postgres
  host: localhost
  port: 5432
  name: Simple_Bank
  user: admin
  password: nnphan2126
  sslmode: disable
  max_idle_conns: 10 #// Số lượng kết nối tối đa có thể được giữ trong pool khi không sử dụng
  max_open_conns: 100 #// Số lượng kết nối tối đa có thể được mở đồng thời
  conn_max_lifetime: 3600 #// Thời gian tối đa mà một kết nối có thể tồn tại trước khi bị đóng và thay thế bằng một kết nối mới

logger:
  log_level: debug
  log_format: text
  file_log_name: ./storage/logs/dev.001.log
  max_size: 10 #// megabytes
  max_backups: 3 #// days
  max_age: 28 #// days
  compress: true
